import Navmenu from '@/components/nav-menu';
import { Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${geistMono.variable} ${geistMono.variable} antialiased overflow-hidden overscroll-none`}>
        <Navmenu />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
